model_list:
  - model_name: Lucie
    litellm_params:
      model: openai/lucie-7b-instruct
      api_base: os.environ/BASE_URL
      api_key: os.environ/LUCIE_API_KEY_01
  - model_name: Lucie
    litellm_params:
      model: openai/lucie-7b-instruct
      api_base: os.environ/BASE_URL
      api_key: os.environ/LUCIE_API_KEY_02
  - model_name: Lucie
    litellm_params:
      model: openai/lucie-7b-instruct
      api_base: os.environ/BASE_URL
      api_key: os.environ/LUCIE_API_KEY_03
  - model_name: Lucie
    litellm_params:
      model: openai/lucie-7b-instruct
      api_base: os.environ/BASE_URL
      api_key: os.environ/LUCIE_API_KEY_04
  - model_name: Lucie
    litellm_params:
      model: openai/lucie-7b-instruct
      api_base: os.environ/BASE_URL
      api_key: os.environ/LUCIE_API_KEY_05


router_settings:
  routing_strategy: simple-shuffle # Literal["simple-shuffle", "least-busy", "usage-based-routing","latency-based-routing"], default="simple-shuffle"

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL_LITELLM
  # enforce_user_param: True


# postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}


# litellm_settings:
#   # Logging/Callback settings
#   success_callback: ["langfuse"]  # list of success callbacks
#   request_timeout: 60 # (int) llm requesttimeout in seconds. Raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout 

#   cache: true 
#   cache_params:        # set cache params for redis
#     type: redis
#     ttl: 600 # will be cached on redis for 600s