services:  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      # - ./certbot:/etc/nginx/certbot
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] # Only on manager
    networks:
      - lucie-network

networks:
  lucie-network:
    external: true