

services:
  pipelines:
    build: 
      context: .
      dockerfile: dockerfile.pipelines
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PIPELINES_URLS=https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py
      - PORTKEY_API_KEY=${PORTKEY_API_KEY}
      - POETRY_VIRTUALENVS_PATH=/app/${ENVS_PATH}/${VENV_NAME}
      - POETRY_VIRTUALENVS_CREATE=true
      - POETRY_VIRTUALENVS_IN_PROJECT=false
      - HOST=${HOST}
      - PORT=${PORT}
    volumes:
      - pipelines:/app/pipelines
      - ${PWD}/pyproject.toml:/app/pyproject.toml
      - ${PWD}/poetry.lock:/app/poetry.lock
      - venv:/app/${ENVS_PATH}/${VENV_NAME}
    env_file:
      - .env.compose


    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      bash -c "
        echo 'PATH: $PATH' && \

        if [ ! -f poetry.lock ] || [ pyproject.toml -nt poetry.lock ]; then
          echo 'Installing dependencies...' && \
          poetry env use python3.12 && \
          poetry install --no-interaction -vv --no-root;
        else
          echo 'Dependencies are up to date';
        fi && \
        echo 'Current environment variables:' && \
        printenv && \
        echo 'Starting pipelines...' && \
        poetry run bash start.sh
      "
volumes:
  pipelines:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/pipelines/pipelines'



  venv:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/${ENVS_PATH}'




  