services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    volumes:
      - /mnt/searxng:/etc/searxng
    restart: always
    networks:
      - lucie-network
networks:
  lucie-network:
    external: true